#!/bin/sh

if [ ! -d "/app/Dropbox/$DROPBOX_FOLDER" ] ; then
  echo "Ignoring, no \"$DROPBOX_FOLDER\" folder exists yet"
  exit 0
fi

rm -rf "/app/public.temp"
if ! cp -R /app/Dropbox/$DROPBOX_FOLDER /app/public.temp ; then
  exit 0
fi

rm -rf "/app/public"
mv "/app/public.temp" "/app/public"
